### ISSUE TITLE
Igraph does not build with macOS clang 12  (XCode 12)

### ISSUE THREAD

**Issue by dimpase** [igraph/igraph#1547]
**Describe the bug**
Igraph does not build with macOS clang 12 compiler (in XCode 12). A workaround is to
```
export CFLAGS="$CFLAGS -Wno-strict-prototypes -Wno-implicit-function-declaration"
```

**To reproduce**
start the build on macOS 10.15 (or macOS 11) with latest Xcode, and see at some point the error with CHOLMOD code:
```
...
/bin/bash ../libtool  --tag=CC   --mode=compile clang -DHAVE_CONFIG_H -I. -I..   -O3 -DIGRAPH_VERIFY_FINALLY_STACK=0 -I../include -I../include -I../src/CHOLMOD/Include -I../src/CHOLMOD/Include -I../src/AMD/Include -I../src/AMD/Include -I../src/COLAMD/Include -I../src/COLAMD/Include -I../src/SuiteSparse_config -I../src/SuiteSparse_config -DNPARTITION -DNTIMER -DNCAMD -Wall  -I../src/prpack -DPRPACK_IGRAPH_SUPPORT -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -O3 -c -o AMD/Source/libigraph_la-amd_1.lo `test -f 'AMD/Source/amd_1.c' || echo './'`AMD/Source/amd_1.c
In file included from CHOLMOD/Supernodal/cholmod_super_numeric.c:80:
CHOLMOD/Supernodal/t_cholmod_super_numeric.c:510:17: error: implicit declaration of function 'dsyrk_' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                BLAS_dsyrk ("L", "N",
                ^
 ../src/CHOLMOD/Include/cholmod_blas.h:331:2: note: expanded from macro 'BLAS_dsyrk'
         BLAS_DSYRK (uplo, trans, &N, &K, alpha, A, &LDA, beta, C, &LDC) ; \
         ^
 ../src/CHOLMOD/Include/cholmod_blas.h:132:20: note: expanded from macro 'BLAS_DSYRK'
 #define BLAS_DSYRK igraphdsyrk_
                   ^
 ./igraph_lapack_internal.h:86:29: note: expanded from macro 'igraphdsyrk_'
    #define igraphdsyrk_    dsyrk_
                            ^
```

**Version information**
latest release 0.8.3. on GitHub

export CFLAGS="$CFLAGS -Wno-strict-prototypes -Wno-implicit-function-declaration"

**Comment by szhorvat** [comment]
Thanks for noting this. 

If you can, please test this with the `develop` branch and let us know if the issue is present there as well. Instructions are at https://igraph.discourse.group/t/draft-document-for-installation-with-cmake/504

Personally, I think that there should be a 0.8.4 release to correct this even before 0.9 is out (might take a while).

**Comment by ntamas** [comment]
Thanks for the report! We have recently switched from autotools to CMake in the development branch and also fixed lots of compiler warnings and errors (also on macOS). Can you try compiling the development branch and report what you found? I'm asking because I'm also using Clang 12 on macOS 10.15 and it works fine for me.

**Comment by szhorvat** [comment]
@ntamas I've heard reports from others too that on Big Sur, Apple Clang no longer tolerates implicit declarations. Thus, a 0.8.4 may not be a bad idea. We need to check if there are issues with homebrew / MacPorts.

**Comment by ntamas** [comment]
See [Homebrew's Big Sur compatibility progress here](https://github.com/Homebrew/brew/issues/7857), FYI.

**Comment by dimpase** [comment]
> on Big Sur, Apple Clang no longer tolerates implicit declarations

this is not limited to Big Sur (aka macOS 11), it's in the latest XCode update. E.g. I get these errors on macOS 10.15.7.

**Comment by ntamas** [comment]
@dimpase what's the exact Clang version on your end? `Apple clang version 12.0.0 (clang-1200.0.32.27)` is okay here; I'm just about to check for Xcode updates.

**Comment by dimpase** [comment]
Same XCode here, but notice that the errors come from SuiteSparse code that you vendor. No wonder that with external SuiteSparse (as by default happens on `develop` branch) you don't see it.

**Comment by ntamas** [comment]
Ah, I figured out in the meanwhile! The entire `CHOLMOD` folder is unnecessary (igraph does not use anything from those routines) so we have removed that folder from the `develop` branch when we re-wrote the build system for CMake.

@szhorvat @vtraag  What do you think, how shall we deal with this? For me the easiest option seems to be to remove `CHOLMOD` and related stuff from the source tree in the `master` branch and then get 0.8.4 out quickly to fix this.

**Comment by dimpase** [comment]
Not sure it's CHOLMOD only, it could be other vendored SuiteSparse modules (AMD, etc) as well.

**Comment by szhorvat** [comment]
I am pretty sure that the `develop` branch version does not have this problem because we use `-Wall -Wextra -pedantic -Werror` so it should error with any compiler. I am assuming that one of `-Wall -Wextra -pedantic` must enable this warning.

**Comment by szhorvat** [comment]
> @szhorvat @vtraag What do you think, how shall we deal with this? For me the easiest option seems to be to remove `CHOLMOD` and related stuff from the source tree in the `master` branch and then get 0.8.4 out quickly to fix this.

I'm not so familiar with autotools, and it's hard for me to judge how easy it is to strip out all the unused SuiteSparse modules, incuding SuiteSparse_config. I would go for the lowest risk change for 0.8.4, which I hope to be the very last 0.8-series release. I.e., just disable these warnings/errors on the relevant compilers.

**Comment by szhorvat** [comment]
For reference, the MacPorts status can be followed here:

https://ports.macports.org/port/igraph/summary

Click on a macOS version to see compilation output and warnings/errors. It is not yet ready for macOS 11.0.

**Comment by dimpase** [comment]
> Can you try compiling the development branch and report what you found?

this works fine for me  (with lots of packages from Homebrew, only Arpack gets vendored.)

**Comment by szhorvat** [comment]
> this works fine for me (with lots of packages from Homebrew, only Arpack gets vendored.)

Great to hear! Could you please try with all-vendored libraries as well?

Assuming you're in the `igraph` directory, with the `develop` branch checked out, here's a complete list of commands to compile this way, and run the unit tests:

```
git clean -fdx
mkdir build
cd build
cmake .. -DIGRAPH_USE_INTERNAL_BLAS=1 -DIGRAPH_USE_INTERNAL_LAPACK=1 -DIGRAPH_USE_INTERNAL_ARPACK=1 -DIGRAPH_USE_INTERNAL_GLPK=1 -DIGRAPH_USE_INTERNAL_CXSPARSE=1 -DIGRAPH_GMP_SUPPORT=1 -DIGRAPH_GLPK_SUPPORT=1
cmake --build . --target check
```

**Comment by ntamas** [comment]
This should be fixed in 10afd6c with XCode 12.2 and `clang` 12.0.0 (`Apple clang version 12.0.0 (clang-1200.0.32.27)`). We can make a quick 0.8.4 release to fix things up for macOS but it would be great if we could test it in advance with MacPorts and Homebrew somehow.

**Comment by dimpase** [comment]
it's perfectly possible, and cost nothing, to run such tests with GitHub Actions. We test SageMath this way, see
https://github.com/sagemath/sage/blob/222059565bc2166f29c50a6d85db7992589098c2/.github/workflows/tox.yml#L105

**Comment by ntamas** [comment]
igraph 0.8.4 is released, which should fix the build problems on macOS with XCode 12.2.
