### ISSUE TITLE
Cannot compile the latest R package on Ubuntu 16.04

### ISSUE THREAD

**Issue by argymeg** [igraph/igraph#1019]
I am trying to install igraph in R 3.4.1, on two different installations of Ubuntu 16.04 and it consistently fails with these messages:

```
gcc -std=gnu99 -I/usr/share/R/include -DNDEBUG     -DUSING_R -I. -Iinclude -Ics -Iglpk -Iplfit -ICHOLMOD/Include -IAMD/Include -ICOLAMD/Include -ISuiteSparse_config -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g -DNDEBUG -DNPARTITION -DNTIMER -DNCAMD -DNPRINT -DPACKAGE_VERSION=\"1.1.1\" -DINTERNAL_ARPACK -DIGRAPH_THREAD_LOCAL=/**/ -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c foreign-graphml.c -o foreign-graphml.o
foreign-graphml.c: In function ‘igraph_write_graph_graphml’:
foreign-graphml.c:1408:46: error: expected ‘)’ before ‘GRAPHML_NAMESPACE_URI’
   ret=fprintf(outstream, "<graphml xmlns=\"" GRAPHML_NAMESPACE_URI "\"\n");
                                              ^~~~~~~~~~~~~~~~~~~~~
foreign-graphml.c:1412:59: error: expected ‘)’ before ‘GRAPHML_NAMESPACE_URI’
   ret=fprintf(outstream, "         xsi:schemaLocation=\"" GRAPHML_NAMESPACE_UR  "\n");
                                                           ^~~~~~~~~~~~~~~~~~~~
foreign-graphml.c:1414:38: error: expected ‘)’ before ‘GRAPHML_NAMESPACE_URI’
   ret=fprintf(outstream, "         " GRAPHML_NAMESPACE_URI "/1.0/graphml.xsd\">\n");
                                      ^~~~~~~~~~~~~~~~~~~~~
/usr/lib/R/etc/Makeconf:159: recipe for target 'foreign-graphml.o' failed
make: *** [foreign-graphml.o] Error 1
ERROR: compilation failed for package ‘igraph’
```
It does compile fine on Arch so I tried installing gcc-7, but it didn't help.
If it helps, the failure point does seem to have been introduced with the latest commit to this file ([ec7db3b](https://github.com/igraph/igraph/commit/ec7db3bc8c95e9d265680743e35d84cf31031cbc)).

Edit: I can confirm reverting this commit fixes the issue.

**Comment by argymeg** [comment]
I can confir

**Comment by jyoti59n** [comment]
Hi. I'm getting the same error while using R 3.3.2 on Ubuntu 14.04 & sense this error has crept in from the latest commit.

**Comment by gaborcsardi** [comment]
@jyoti59n @argymeg Can one of you tell me *exactly* how you are compiling it? Where you get the file from? What platform? What R version?

**Comment by argymeg** [comment]
I'm simply running install.packages("igraph") from the R console. Ubuntu Server 16.04.2 LTS, x86_64, tested with R versions 3.2.3 and 3.4.1.

**Comment by jyoti59n** [comment]
I'm trying it from Ubuntu 14.04 using R 3.3.2. Basically install.packages("igraph") - gives me the error. Thanks for the quick response.

**Comment by gaborcsardi** [comment]
How did you in install R? Which version of igraph is this?

**Comment by argymeg** [comment]
r-base-dev 3.2.3 from the official xenial repository, r-base-dev 3.4.1 from the [CRAN Ubuntu repository](https://cran.r-project.org/bin/linux/ubuntu/). igraph version is 1.1.2.

**Comment by argymeg** [comment]
In case it helps you with troubleshooting, I can also confirm the same happens on a fresh install of Fedora 26, with R 3.4.1 from the official repository and igraph 1.1.2.

**Comment by gaborcsardi** [comment]
The interesting thing is that igraph is apparently fine on all CRAN platforms, including debian and fedora:
https://cran.r-project.org/web/checks/check_results_igraph.html

Are you sure that you have the system requirements installed, e.g. libxml2-devel?

**Comment by jyoti59n** [comment]
I suspected this & re-installed libxml2 - but problem persists. Another thing when I try to use an earlier build from the CRAN archive it works like a charm.

**Comment by gaborcsardi** [comment]
@jyoti59n You need `libxml2-dev`, not just `libxml2`. 

I think the older versions turn off graphml support if there is no libxml2, and they don't give any errors.

**Comment by argymeg** [comment]
@gaborcsardi You got me. That was it. Argh.
It might be a good idea to make compilation fail at the configuration stage with a warning if these two are missing.
Nevertheless, many thanks for your time and patience. Feel free to close the issue if @jyoti59n confirms it works for them.

**Comment by jyoti59n** [comment]
Oh perfect - works for me as well(yes libxml2-dev instead of libxml2 solved it). Thanks a ton @gaborcsardi - pls close the issue. Thanks @argymeg.

**Comment by ydorant** [comment]
Hey! I had the same pb with igraph and this solved my pb !
-> Linux Mint Cinnamon - R 3.4.1 - R studio
install.packages("igraph") failed to install...

I eat my shell with your cmd libs "sudo apt-get install libxml2-dev libxml2" and the installation library work well !
Thanks

**Comment by FelixTheStudent** [comment]
Error persists for me, "sudo apt-get install libxml2-dev libxml2" does not solve the issue.

Error encountered at:
`install.packages("igraph")`  in R-3.4.3 on Ubuntu 14.04.5 LTS

**Comment by Batstaph** [comment]
Same error in Ubuntu 16.04 LTS, same failure to fix with libxml2-dev etc.
I'm not savvy enough to apply a manual patch to fix this. Any other solutions?

**Comment by FelixTheStudent** [comment]
Update: my work-around was to install the devel-version, which for some reason worked. That's enough for me right now, here's the code to do it:
`  devtools::install_github("gaborcsardi/pkgconfig")
  devtools::install_github("igraph/rigraph")`

**Comment by ntamas** [comment]
@FelixTheStudent @Batstaph are/were you getting the same error message as the one reported in the first comment of this issue?

**Comment by Batstaph** [comment]
Yes I get the same error message.  I've just tried to install the devel version but failed at the first hurdle:
install.packages("devtools")
Warning: unable to access index for repository https://mran.microsoft.com/snapshot/2018-01-01/src/contrib:
  Line starting '<head> ...' is malformed!
Warning message:
package ‘devtools’ is not available (for R version 3.4.3)
It looks as if there's some kind of problem redirecting to a new website. I will plug on.....

**Comment by ntamas** [comment]
The issue that has caused the original error message in the post has already been fixed in the codebase. No new version of the C core has been released yet, so a permanent solution would be simply to release a new version of the C core (which is up to @gaborcsardi to decide). As far as I know, the development version of the R package also includes the fix. The error message you get regarding the index of the repository is unrelated; the repository that you are using seems to be down, so switching to the official CRAN repo would probably help.
