### ISSUE TITLE
Does not compile with old GCC such as version 4.8

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2138]
igraph does not compile with GCC 4.8 because:

```
/home/szhorvat/Repos/igraph/src/misc/conversion.c: In function ‘igraph_to_directed’:
/home/szhorvat/Repos/igraph/src/misc/conversion.c:471:9: warning: implicit declaration of function ‘__builtin_mul_overflow’ [-Wimplicit-function-declaration]
         IGRAPH_SAFE_MULT(no_of_edges, 4, &size);
         ^
```

Our check for whether these builtins are available is not sufficiently robust and needs to be improved, either by adding version checks on GCC/Clang/Intel, or better: using CMake to test for the presence of these builtins.

**Comment by szhorvat** [comment]
These were added [in GCC 5](https://gcc.gnu.org/gcc-5/changes.html), but we don't want to figure out the same for Clang / Intel, so a CMake-based test is best.
